/*Contenido para la tabla de Provincias de España*/
INSERT INTO provincias (id, nombre)
VALUES ('00', ''), /*Como es obligatorio algún valor, por si no sabe la provincia */
       ('01', 'Álava'),
       ('02', 'Albacete'),
       ('03', 'Alicante'),
       ('04', 'Almería'),
       ('05', 'Ávila'),
       ('06', 'Badajoz'),
       ('07', 'Baleares (Illes)'),
       ('08', 'Barcelona'),
       ('09', 'Burgos'),
       ('10', 'Cáceres'),
       ('11', 'Cádiz'),
       ('12', 'Castellón'),
       ('13', 'Ciudad Real'),
       ('14', 'Córdoba'),
       ('15', 'A Coruña'),
       ('16', 'Cuenca'),
       ('17', 'Girona'),
       ('18', 'Granada'),
       ('19', 'Guadalajara'),
       ('20', 'Guipúzcoa'),
       ('21', 'Huelva'),
       ('22', 'Huesca'),
       ('23', 'Jaén'),
       ('24', 'León'),
       ('25', 'Lleida'),
       ('26', 'La Rioja'),
       ('27', 'Lugo'),
       ('28', 'Madrid'),
       ('29', 'Málaga'),
       ('30', 'Murcia'),
       ('31', 'Navarra'),
       ('32', 'Ourense'),
       ('33', 'Asturias'),
       ('34', 'Palencia'),
       ('35', 'Las Palmas'),
       ('36', 'Pontevedra'),
       ('37', 'Salamanca'),
       ('38', 'Santa Cruz de Tenerife'),
       ('39', 'Cantabria'),
       ('40', 'Segovia'),
       ('41', 'Sevilla'),
       ('42', 'Soria'),
       ('43', 'Tarragona'),
       ('44', 'Teruel'),
       ('45', 'Toledo'),
       ('46', 'Valencia'),
       ('47', 'Valladolid'),
       ('48', 'Vizcaya'),
       ('49', 'Zamora'),
       ('50', 'Zaragoza'),
       ('51', 'Ceuta'),
       ('52', 'Melilla'),
       ('99', 'Internacional');

/* Contenido de la tabla direcciones */
INSERT INTO direcciones (direccion, id_provincia)
VALUES ('Calle Málaga', '29'),
       ('Calle Cordoba', '29'),
       ('Calle Marques de Larios', '29');

/* Contenido de la tabla usuarios */
INSERT INTO usuarios (nombre, apellido1, apellido2, fecha_nacimiento, id_direccion,is_Admin, email, clave)
VALUES ('Pepe','Lopez','Lopez','2000-10-10',1,true,'pepe@hotmail.com','123456'),
       ('Juan','Martín','Garcia','1990-05-12',2,false,'juan@hotmail.com','654321'),
       ('Antonio','Perez','Perez','1999-01-20',3,false,'antonio@hotmail.com','112233');